kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
          app: hello
    spec:
      containers:
        - name: hello
          image: >-
            quay.io/lozanotux/hello-kubernetes:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MESSAGE
              value: {{ .Values.hello.message }}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always