kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
          app: hello
    spec:
      containers:
        - name: hello
          image: >-
            quay.io/lozanotux/hello:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MSG
              value: HOLA WORKSHOP GITOPS
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always